<a href="https://colab.research.google.com/github/satyamnewale/numpy-notebooks/blob/main/dot_add_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create arrays and inspect metadata

In [11]:

import numpy as np

one_D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
two_D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
three_D = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[8,10],[11,12]]])

print(f"Shape of one_D (element):",one_D.shape," Dimenions of 0ne_D:",one_D.ndim," dtype:",one_D.dtype," size:",one_D.size)
print(f"Shape of two_D (row X column):",two_D.shape," Dimenions of two_D:",two_D.ndim," dtype:",two_D.dtype," size:",two_D.size)
print(f"Shape of three_D (depth X row X column):",three_D.shape," Dimenions of three_D:",three_D.ndim," dtype:",three_D.dtype," size:",three_D.size)


Shape of one_D (element): (12,)  Dimenions of 0ne_D: 1  dtype: int64  size: 12
Shape of two_D (row X column): (4, 3)  Dimenions of two_D: 2  dtype: int64  size: 12
Shape of three_D (depth X row X column): (3, 2, 2)  Dimenions of three_D: 3  dtype: int64  size: 12


Reshape, transpose and flatten

In [28]:
import numpy as np

one_D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
two_D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
three_D = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[8,10],[11,12]]])

# reshaping one_D
one_D_to_two_D = one_D.reshape(4,3)
one_D_to_three_D = one_D.reshape(2,2,3)

# reshape two_D and flatten
two_D_to_one_D = two_D.flatten()
two_D_to_three_D = two_D.reshape(3,4)
two_D_to_two_D = two_D.reshape(6,2)

#reshape and flatten three_D
three_D_to_one_D = three_D.flatten()
three_D_to_two_D = three_D.reshape(4,3)
three_D_to_three_D = three_D.reshape(2,3,2)

#comparisions
print(f"one_D value eqauls one_D_to_two_D: {one_D.size == one_D_to_two_D.size}")
print(f"one_D value eqauls one_D_to_three_D: {one_D.size == one_D_to_three_D.size}")
print(f"two_D value eqauls two_D_to_one_D: {two_D.size == two_D_to_one_D.size}")
print(f"two_D value eqauls two_D_to_two_D: {two_D.size == two_D_to_two_D.size}")
print(f"two_D value eqauls two_D_to_three_D: {two_D.size == two_D_to_three_D.size}")
print(f"three_D value eqauls three_D_to_one_D: {three_D.size == three_D_to_one_D.size}")
print(f"three_D value eqauls three_D_to_two_D: {three_D.size == three_D_to_two_D.size}")
print(f"three_D value eqauls three_D_to_three_D: {three_D.size == three_D_to_three_D.size}")

#dimensions
print("-------------------------------------------------------------------------------")
print(f"one_D dimension eqauls one_D_to_two_D: {one_D.ndim == one_D_to_two_D.ndim}")
print(f"one_D dimension eqauls one_D_to_three_D: {one_D.ndim == one_D_to_three_D.ndim}")
print(f"two_D dimension eqauls two_D_to_one_D: {two_D.ndim == two_D_to_one_D.ndim}")
print(f"two_D dimension eqauls two_D_to_two_D: {two_D.ndim == two_D_to_two_D.ndim}")
print(f"two_D dimension eqauls two_D_to_three_D: {two_D.ndim == two_D_to_three_D.ndim}")
print(f"three_D dimension eqauls three_D_to_one_D: {three_D.ndim == three_D_to_one_D.ndim}")
print(f"three_D dimension eqauls three_D_to_two_D: {three_D.ndim == three_D_to_two_D.ndim}")
print(f"three_D dimension eqauls three_D_to_three_D: {three_D.ndim == three_D_to_three_D.ndim}")
print("-------------------------------------------------------------------------------")
#transpose of all
print("oneD and oneD.T-(no changes)------------------------------------------------")
print(one_D,one_D.T)
print("twoD and twoD.T-------------------------------------------------------------")
print(two_D,two_D.T)
print("threeD and threeD.T---------------------------------------------------------")
print(three_D,three_D.T)
print("oneD_to_twoD and oneD_to_twoD.T---------------------------------------------")
print(one_D_to_two_D,one_D_to_two_D.T)
print("one_D_to_three_D and one_D_to_three_D.T-------------------------------------")
print(one_D_to_three_D,one_D_to_three_D.T)
print("two_D_to_one_D and two_D_to_one_D.T-(no change)-----------------------------")
print(two_D_to_one_D,two_D_to_one_D.T)
print("two_D_to_three_D and two_D_to_three_D.T-------------------------------------")
print(two_D_to_three_D,two_D_to_three_D.T)
print("two_D_to_two_D and two_D_to_two_D.T-----------------------------------------")
print(two_D_to_two_D,two_D_to_two_D.T)
print("-three_D_to_one_D and three_D_to_one_D.T-(no change)------------------------")
print(three_D_to_one_D,three_D_to_one_D.T)
print("three_D_to_two_D and three_D_to_two_D.T-------------------------------------")
print(three_D_to_two_D,three_D_to_two_D.T)
print("three_D_to_three_D and three_D_to_three_D.T---------------------------------")
print(three_D_to_three_D,three_D_to_three_D.T)

#row major and column major
print("Column major twoD-----------------------------------------------------------")
print(two_D.flatten(order='F'))
print("Row major twoD--------------------------------------------------------------")
print(two_D.flatten(order='C'))
print("Column major threeD---------------------------------------------------------")
print(three_D.flatten(order='F'))
print("Row major threeD------------------------------------------------------------")
print(three_D.flatten(order='C'))

one_D value eqauls one_D_to_two_D: True
one_D value eqauls one_D_to_three_D: True
two_D value eqauls two_D_to_one_D: True
two_D value eqauls two_D_to_two_D: True
two_D value eqauls two_D_to_three_D: True
three_D value eqauls three_D_to_one_D: True
three_D value eqauls three_D_to_two_D: True
three_D value eqauls three_D_to_three_D: True
-------------------------------------------------------------------------------
one_D dimension eqauls one_D_to_two_D: False
one_D dimension eqauls one_D_to_three_D: False
two_D dimension eqauls two_D_to_one_D: False
two_D dimension eqauls two_D_to_two_D: True
two_D dimension eqauls two_D_to_three_D: True
three_D dimension eqauls three_D_to_one_D: False
three_D dimension eqauls three_D_to_two_D: False
three_D dimension eqauls three_D_to_three_D: True
-------------------------------------------------------------------------------
oneD and oneD.T-(no changes)------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12] [ 1  2  3  4

Broadcasting hands-on

In [35]:
import numpy as np

# ---------------------------------------------------------
# Base arrays
# ---------------------------------------------------------
scalar = 10
one_D = np.arange(1, 13)                                      # shape (12,)
two_D = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])                              # shape (4, 3)
three_D = np.array([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]],
                    [[9, 10],
                     [11, 12]]])                              # shape (3, 2, 2)

# ---------------------------------------------------------
# 1️⃣ Scalar Broadcasting
# ---------------------------------------------------------
print("---- Scalar Broadcasting ----")
print("one_D + scalar:\n", one_D + scalar)
print("two_D * scalar:\n", two_D * scalar)
print("three_D - scalar:\n", three_D - scalar)

# ---------------------------------------------------------
# 2️⃣ 1D ↔ 1D
# ---------------------------------------------------------
print("\n---- 1D ↔ 1D ----")
b = np.arange(12, 0, -1)
print("one_D + b:\n", one_D + b)
print("one_D * np.array([2]):\n", one_D * np.array([2]))  # broadcasts scalar shape (1,)

# ---------------------------------------------------------
# 3️⃣ 1D ↔ 2D
# ---------------------------------------------------------
print("\n---- 1D ↔ 2D ----")
# (4,3) + (3,) → broadcast across rows
print("two_D + np.array([10,20,30]):\n", two_D + np.array([10, 20, 30]))

# (4,3) + (4,1) → broadcast across columns
print("two_D + np.array([[100],[200],[300],[400]]):\n",
      two_D + np.array([[100],[200],[300],[400]]))

# ---------------------------------------------------------
# 4️⃣ 2D ↔ 3D
# ---------------------------------------------------------
print("\n---- 2D ↔ 3D ----")
twoD = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])                                    # shape (3,2)
threeD = np.array([[[1],[2]],
                   [[3],[4]],
                   [[5],[6]]])                               # shape (3,2,1)

# Reshape twoD to (3, 2, 1) for compatible broadcasting with threeD (3, 2, 1)
twoD_reshaped = twoD.reshape(3, 2, 1)
print("twoD_reshaped + threeD (shapes (3,2,1) + (3,2,1)):\n", twoD_reshaped + threeD)

# ---------------------------------------------------------
# 5️⃣ 1D ↔ 3D
# ---------------------------------------------------------
print("\n---- 1D ↔ 3D ----")
# To broadcast, inner dimensions must match
one_D_short = np.array([1, 2])                               # shape (2,)
print("three_D + one_D_short.reshape(1,1,2):\n", three_D + one_D_short.reshape(1,1,2))

# ---------------------------------------------------------
# 6️⃣ Verifying incompatible case
# ---------------------------------------------------------
print("\n---- Incompatible Broadcasting ----")
try:
    print(one_D + three_D)
except ValueError as e:
    print("Error:", e)

# ---------------------------------------------------------
# 7️⃣ Summary Check: shapes
# ---------------------------------------------------------
print("\nShapes Summary:")
print("scalar:", np.shape(scalar))
print("one_D:", one_D.shape)
print("two_D:", two_D.shape)
print("three_D:", three_D.shape)
print("twoD:", twoD.shape)
print("threeD:", threeD.shape)

---- Scalar Broadcasting ----
one_D + scalar:
 [11 12 13 14 15 16 17 18 19 20 21 22]
two_D * scalar:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
three_D - scalar:
 [[[-9 -8]
  [-7 -6]]

 [[-5 -4]
  [-3 -2]]

 [[-1  0]
  [ 1  2]]]

---- 1D ↔ 1D ----
one_D + b:
 [13 13 13 13 13 13 13 13 13 13 13 13]
one_D * np.array([2]):
 [ 2  4  6  8 10 12 14 16 18 20 22 24]

---- 1D ↔ 2D ----
two_D + np.array([10,20,30]):
 [[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]
two_D + np.array([[100],[200],[300],[400]]):
 [[101 102 103]
 [204 205 206]
 [307 308 309]
 [410 411 412]]

---- 2D ↔ 3D ----
twoD_reshaped + threeD (shapes (3,2,1) + (3,2,1)):
 [[[ 2]
  [ 4]]

 [[ 6]
  [ 8]]

 [[10]
  [12]]]

---- 1D ↔ 3D ----
three_D + one_D_short.reshape(1,1,2):
 [[[ 2  4]
  [ 4  6]]

 [[ 6  8]
  [ 8 10]]

 [[10 12]
  [12 14]]]

---- Incompatible Broadcasting ----
Error: operands could not be broadcast together with shapes (12,) (3,2,2) 

Shapes Summary:
scalar: ()
one_D: (12,)
two_D: (4, 3)
three

1. broadcasting with singular value is easy .
2. but broadccasting a vector with other vector should has dimensionally similarity.
3. Or one of the diamension match others diamension say (mXn) and (nXp) where n are similar
4. similar goes for matrix and vectors of 1D, 2D, 3D etc.
5. similar diamension matrix or vectors broadcasting in easy whereas not for disimilar checking shape and diamensions become important.

In [39]:
import numpy as np

one_D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
oneD = np.arange(1, 13)

#copy and view
one_D_copy = one_D.copy()
oneD_view = oneD.view()

#change in copy and view
one_D_copy[0] = 100
oneD_view[0] = 100

#see results
print(f"changes in copy- one_D :{one_D} and one_D_copy:{one_D_copy}")
print(f"changes in view- oneD :{oneD} and oneD_view:{oneD_view}")
#

changes in copy- one_D :[ 1  2  3  4  5  6  7  8  9 10 11 12] and one_D_copy:[100   2   3   4   5   6   7   8   9  10  11  12]
changes in view- oneD :[100   2   3   4   5   6   7   8   9  10  11  12] and oneD_view:[100   2   3   4   5   6   7   8   9  10  11  12]


1. always use copy so original value will never change
2. view is good but it will change original value
3. always keeping copy is best for future execution or may required for other porcess.

matrix_dot_add without loops

In [58]:
import numpy as np

def dot_add(matrix_list, mat3, flag):
    # Check input
    if len(matrix_list) != 2:
        return "Error: matrix_list must contain exactly two matrices."

    try:
        mat1, mat2 = matrix_list

        # --- Check dot compatibility ---
        if mat1.shape[1] != mat2.shape[0]:
            if flag.lower() == "flex":
                # Try reshaping flexibly
                try:
                    mat2 = mat2.reshape(mat1.shape[1], -1)
                except ValueError:
                    return "Size of matrix is not compatible for dot product."
            else:
                return "Size of matrix is not compatible for dot product."

        # Perform dot product
        dot_product = np.dot(mat1, mat2)

        # --- Addition compatibility ---
        if dot_product.shape != mat3.shape:
            if flag.lower() == "flex":
                try:
                    # Try to broadcast safely
                    broadcast_shape = np.broadcast_shapes(dot_product.shape, mat3.shape)
                    mat3_b = np.broadcast_to(mat3, broadcast_shape)
                    dot_b = np.broadcast_to(dot_product, broadcast_shape)
                    return dot_b + mat3_b
                except ValueError:
                    return "Size of matrix is not compatible for addition."
            else:
                return "Size of matrix is not compatible for addition."
        else:
            return dot_product + mat3

    except ValueError as e:
        return f"Error: {e}"


# Example 1
mat1 = np.array([[1, 2], [3, 4], [5, 6]])
mat2 = np.array([[7, 8, 9], [10, 11, 12]])
mat3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(dot_add([mat1, mat2], mat3, flag="flex"))

# Example 2
mat_1 = np.array([[1, 2, 3], [4, 5, 6]])
mat_2 = np.array([[7, 8], [9, 10], [11, 12]])
mat_3 = np.array([[1, 2], [3, 4]])
print(dot_add([mat_1, mat_2], mat_3, flag="strict"))

# Example 3
mat__1 = np.array([[1, 2, 3]])
mat__2 = np.array([[4, 5, 6]])
mat__3 = np.array([[7, 8, 9]])
print(dot_add([mat__1, mat__2], mat__3, flag="strict"))

# Example 4
A1 = np.array([[1, 2, 3], [4, 5, 6]])
B1 = np.array([[7, 8, 9, 10, 11, 12]])
C1 = np.array([[1, 2, 3], [4, 5, 6]])
print(dot_add([A1, B1], C1, flag="flex"))

# Example 5
A2 = np.array([[1, 2], [3, 4]])
B2 = np.array([[5, 6, 7]])
C2 = np.array([[10, 20, 30], [40, 50, 60]])
print(dot_add([A2, B2], C2, flag="flex"))

# Example 6
A3 = np.array([[2, 4, 6]])
B3 = np.array([[1], [2], [3]])
C3 = np.array([[1, 2, 3]])
print(dot_add([A3, B3], C3, flag="flex"))


[[ 28  32  36]
 [ 65  73  81]
 [102 114 126]]
[[ 59  66]
 [142 158]]
Size of matrix is not compatible for dot product.
Size of matrix is not compatible for addition.
Size of matrix is not compatible for dot product.
[[29 30 31]]


1. in above code dat and add operation is performed using a function which has option to make matrixs xhangeable and continue operation
2. if flex flag set the matrix will be able convert
*   for dot product if matrix not correct use reshaping
*   for addition operation if matrix not suits then used broadcast_to method
3. broadcast_shape check if broadcasting fo two matrices is possible or not.

