<a href="https://colab.research.google.com/github/satyamnewale/numpy-notebooks/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Understand fundamental linear algebra transformations.

In [55]:
import numpy as np

a = np.array([[2,5,1],[-4,0,-7],[13,5,-9]])
b = np.reshape(a,(3,3))
print(b)
# transpose and determinant
tr = b.T
det = np.linalg.det(b)
print("transpose: ",tr)
print("det : ",det)

# inverse
inv = np.linalg.inv(b)
print("inv: ",inv)

#inverse property check
isTrue = np.allclose(b @ inv, np.eye(3))
print("Is B @ B_inv = I :", isTrue)

#eignvalue and eigenvector
eigenvalues, eigenvectors = np.linalg.eig(b)
print("eigenvalues: ",eigenvalues)
print("eigenvectors: ",eigenvectors)

# eigen validation
for i in range(len(eigenvalues)):
    eigenvalue = eigenvalues[i]
    eigenvector = eigenvectors[:, i]

    left = b @ eigenvector
    right = eigenvalue * eigenvector

    print(f"Eigenvalue {eigenvalue:.3f} → Check:", np.allclose(left, right))

[[ 2  5  1]
 [-4  0 -7]
 [13  5 -9]]
transpose:  [[ 2 -4 13]
 [ 5  0  5]
 [ 1 -7 -9]]
det :  -585.0000000000002
inv:  [[-0.05982906 -0.08547009  0.05982906]
 [ 0.21709402  0.05299145 -0.01709402]
 [ 0.03418803 -0.09401709 -0.03418803]]
Is B @ B_inv = I : True
eigenvalues:  [  1.61872247+7.38396249j   1.61872247-7.38396249j
 -10.23744495+0.j        ]
eigenvectors:  [[-0.09079134-0.46717354j -0.09079134+0.46717354j -0.2619592 +0.j        ]
 [ 0.7197536 +0.j          0.7197536 -0.j          0.47288573+0.j        ]
 [-0.11455943-0.49227706j -0.11455943+0.49227706j  0.84128263+0.j        ]]
Eigenvalue 1.619+7.384j → Check: True
Eigenvalue 1.619-7.384j → Check: True
Eigenvalue -10.237+0.000j → Check: True


In [54]:
import numpy as np

a = np.array([[1,2,3],[2,4,6],[3,6,9]])
b = np.reshape(a,(3,3))
print(b)
# transpose and determinant
tr = b.T
det = np.linalg.det(b)
print("transpose: ",tr)
print("det : ",det)

# inverse
isInvertible = not np.allclose(det, 0)
print("Is matrix invertible?", isInvertible)

#eignvalue and eigenvector
eigenvalues, eigenvectors = np.linalg.eig(b)
print("eigenvalues: ",eigenvalues)
print("eigenvectors: ",eigenvectors)

# eigen validation
for i in range(len(eigenvalues)):
    eigenvalue = eigenvalues[i]
    eigenvector = eigenvectors[:, i]

    left = b @ eigenvector
    right = eigenvalue * eigenvector

    print(f"Eigenvalue {eigenvalue:.3f} → Check:", np.allclose(left, right))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
transpose:  [[1 2 3]
 [2 4 6]
 [3 6 9]]
det :  0.0
Is matrix invertible? False
eigenvalues:  [ 1.40000000e+01  3.58824538e-16 -5.87239501e-16]
eigenvectors:  [[ 0.26726124 -0.11336834  0.6357427 ]
 [ 0.53452248 -0.80883073 -0.72308631]
 [ 0.80178373  0.57700993  0.27014331]]
Eigenvalue 14.000 → Check: True
Eigenvalue 0.000 → Check: True
Eigenvalue -0.000 → Check: True


1. determinant is calculated of square matrix.
2. if determinant of matrix is 0 then it doesnt has inverse matrix.
3. if inverse matrix present then it satisfies A @ A_inv = I.
4. eignvals and eigenvecs if satisfies Av=λv equation then it correct.

